name: Deploy React Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: sudo docker build -t laila22/react-app .
      - name: Publish Image to docker hub
        run: sudo docker push laila22/react-app:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull laila22/react-app:latest 
      - name: Delete old container
        run: sudo docker rm -f react-app-container
      - name: Run Docker Container
        run: sudo docker run -d -p 3000:80 --name react-app-container laila22/react-app